name: spor

on:
  workflow_dispatch: # Manuel başlatma butonu
  schedule:
    # Her 6 saatte bir otomatik olarak yeniden başlatır
    - cron: '0 */6 * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # GitHub'ın izin verdiği maksimum 6 saatlik süre

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: FFmpeg ve Bağımlılıkların Kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install requests

      - name: Canlı Yayını Çalıştır
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
          STREAM_URL: ${{ secrets.STREAM_URL }}
        run: |
          python spor.py
